model:
  lmax: 2
  vecnorm_type: None
  trainable_vecnorm: False
  num_heads: 4
  hidden_channels: 96
  num_rbf: 25
  rbf_type: gauss
  trainable_rbf: False
  activation: silu
  attn_activation: silu
  max_z: 118 # 86 for QCML, 54 for OMol25, 10 for GWSet
  cutoff: 5.0
  num_layers: 3
  max_num_neighbors: 100
  load_model: False
  model_path: None
  transfer_learn: False
data:
  dataset: gwset
  data_path: GWSet
  target: HOMO
  num_train: 1000
  num_val: 100
  num_test: 100
  remove_charged: False
training:
  device: cpu
  log_dir: visnet_logs
  batch_size: 8
  num_epochs: 4
  num_warmup_epochs: 2
  lr_start: 0.00001
  lr_max: 0.0005
  eta_min: 0.00001
  weight_decay: 0.001