model:
  lmax: 2
  vecnorm_type: None
  trainable_vecnorm: False
  num_heads: 4
  hidden_channels: 152
  num_rbf: 38
  rbf_type: gauss
  trainable_rbf: False
  activation: silu
  attn_activation: silu
  max_z: 83
  cutoff: 7.2
  num_layers: 2
  max_num_neighbors: 100
  load_model: False
  model_path: visnet_logs/model.ckpt
  transfer_learn: False
data:
  dataset: gwset
  num_train: 120000
  num_val: 12000
training:
  device: cpu
  log_dir: visnet_logs
  batch_size: 128
  num_epochs: 50
  num_warmup_epochs: 5
  lr_start: 0.000001
  lr_max: 0.0001
  eta_min: 0.000001
  weight_decay: 0.001