model:
  lmax: 1
  vecnorm_type: None
  trainable_vecnorm: False
  num_heads: 4
  hidden_channels: 32
  num_rbf: 25
  rbf_type: gauss
  trainable_rbf: False
  activation: silu
  attn_activation: silu
  max_z: 83
  cutoff: 5.0
  num_layers: 3
  max_num_neighbors: 100
  load_model: False
  model_path: visnet_logs/model.ckpt
  transfer_learn: False
data:
  dataset: gwset
  data_path: GWSet 
  num_train: 1000
  num_val: 100
training:
  device: cpu
  log_dir: visnet_logs
  batch_size: 64
  num_epochs: 55
  num_warmup_epochs: 5
  lr_start: 0.00001
  lr_max: 0.0003
  eta_min: 0.00001
  weight_decay: 0.001