model:
  lmax: 2
  vecnorm_type: None
  trainable_vecnorm: False
  num_heads: 4
  hidden_channels: 128
  num_rbf: 25
  rbf_type: gauss
  trainable_rbf: False
  activation: silu
  attn_activation: silu
  max_z: 83
  cutoff: 5.0
  num_layers: 3
  max_num_neighbors: 100
  load_model: True
  model_path: /workspace/ViSNetGW/gapbse0M128502532_transfer_converged/pretrained.ckpt
  transfer_learn: True
data:
  dataset: qcdge
  data_path: /Volumes/LaCie/QCDGE/for_training/QCDGE
  target: E
  num_train: 400000
  num_val: 41404
  num_test: 0
  remove_charged: False
training:
  device: cuda
  log_dir: visnet_logs
  batch_size: 256
  num_epochs: 75
  num_warmup_epochs: 5
  lr_start: 0.000001
  lr_max: 0.0005
  eta_min: 0.0001
  weight_decay: 0.001